### ISSUE TITLE
INSTALL_CMAKE_DIR no longer works

### ISSUE THREAD

**Issue by radarsat1** [FrictionalContactLibrary/fclib#20]
The debian package was using this to change where cmake files end up.
Perhaps there is a different way to specify it now, but I do not see an option when using CMake curses interface `ccmake` either.
I do see some options are in `InstallPackage.cmake`, that do not show up in `ccmake`, so I think it's intended to work.

In any case, for the record, the debian package currently installs cmake files to `/usr/lib/x86_64-linux-gnu/cmake/FCLib`, which I'm not 100% sure is correct, so it's nice to be able to modify it by an option.

```
sinclairs@58c7965755fb:~/fclib (master)
$ git clean -xfd .
Removing bld/

sinclairs@58c7965755fb:~/fclib (master)
$ mkdir bld; cd bld

sinclairs@58c7965755fb:~/fclib/bld (master)
$ cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/inst -DINSTALL_CMAKE_DIR=$PWD/inst/usr/lib/cmake/FCLIB
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.4") found components: C HL 
-- ====================== Summary ======================
--  Compiler : /usr/bin/cc
--  Sources are in : /home/sinclairs/fclib
--  Project uses MPI : OFF
--  Project uses HDF5 : /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
--  Project will be installed in /home/sinclairs/fclib/bld/inst
-- ====================== ======= ======================
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    INSTALL_CMAKE_DIR


-- Build files have been written to: /home/sinclairs/fclib/bld
```

**Comment by radarsat1** [comment]
Just examining my Ubuntu system a bit, I see that some packages, e.g. glm, pybind11, have cmake files in `/usr/lib/cmake`, and others, e.g., Qt, have them in `/usr/lib/x86_64-linux-gnu/cmake`.

**Comment by radarsat1** [comment]
Okay, I finally figured out that the place to specify this has been changed to the variable ConfigPackageLocation in fclib_setup.cmake.  Sorry, I am not completely up to date on "modern" cmake.  However, I tried setting ConfigPackageLocation from the command line and it doesn't change anything.  From the [docs](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html) I don't see that you are meant to customize this.. perhaps it's okay as-is, I will try it with Siconos and see if the cmake can find the fclib package properly, if so then perhaps it's already installing to the right place.

**Comment by radarsat1** [comment]
Hm, crucially though, in the docs that I pointed to in the previous comment, the ConfigPackageLocation path does *not* contain the version number.

**Comment by radarsat1** [comment]
Okay just tried with Siconos but still an error, for the record this is the error, trying to get to the bottom of it:

```
CMake Error at numerics/CMakeLists.txt:147 (find_package):
  Could not find a configuration file for package "FCLIB" that is compatible
  with requested version "3.0.0".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/fclib-3.1.0/fclib-config.cmake, version: 3.1.0



-- Configuring incomplete, errors occurred!
```

**Comment by radarsat1** [comment]
(Where I temporarily marked the updated package as 3.1.0 just for testing.)

**Comment by radarsat1** [comment]
Okay sorry for the liveblogging here, but if I change version in numerics/CMakeLists.txt to 3.1.0 then it gets past the fclib problems.  Short story, I guess the hardcoded location is fine, as CMake is able to find it there.  It would be better if it only depended on the major version number however.

**Comment by fperignon** [comment]
Hi,

the install process for .cmake files in fclib  is handled by the function configure_package_config_file
(doc : https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html?highlight=config%20package <https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html?highlight=config%20package>)

The INSTALL_DESTINATION  arg  is used for that purpose, 
and set in our case to ConfigPackageLocation

ConfigPackageLocation is set in fclib_setup.cmake : 
set(ConfigPackageLocation lib/cmake/fclib-${PACKAGE_VERSION})


and so, the fclib-config.cmake will be installed in ${CMAKE_INSTALL_PREFIX}/lib/cmake/fclib-VERSIONNUMBER/

Maybe we should use a CACHE variable for ConfigPackageLocation to allow us to control it with the command line.

Concernant siconos, it looks for fclib in numerics CMakeLists.txt with the line

  find_package(FCLIB 3.0.0 CONFIG REQUIRED)

I should find a way to ask for >=3.0.0 rather than equal to 3.0.0

And by the way, the cmake command for siconos should contains something like

-DWITH_FCLIB=ON -DFCLIB_ROOT=/Users/Franck/Softs/install-clang/fclib-mine/

the part with FCLIB_ROOT is optional and required if fclib is not installed in a standard place.

(notice that for some old cmake version, XXX_ROOT must be replaced by XXX_DIR=fullpath to .cmake file,
eg   -DFCLIB_ROOT=/Users/Franck/Softs/install-clang/fclib-mine/lib/cmake/fclib-3.0.0)

Last point, you can find a registry (docker image) ready-to use for siconos, with fclib here :

https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos/container_registry <https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos/container_registry>

does that help ?

**Comment by radarsat1** [comment]
Yes, ok after changing fclib to be SameMajorVersion, then I was able to change Siconos to only ask for version 3, and it worked.  It seems to solve the problem, so I will close this.  Not sure whether it should become a cache variable, let's see if it leads to any other issues I guess.  For now it is okay I think.
